"""
import_layers.py — Bulk-import all tiles.ciesin.app sources into QGIS.

Run this script in the QGIS Python console (Plugins -> Python Console -> open editor,
paste or load this file, then click Run).

Requires:
    - QGIS 3.16+ (QgsVectorTileLayer support)
    - QGIS 3.24+ recommended (better QgsMapBoxGlStyleConverter expression support)
    - style-resolved.json  (generate with: python preprocessing/scripts/resolve_style.py)

Usage:
    1. Edit STYLE_PATH below to point at your local style-resolved.json.
    2. Paste the whole file into the QGIS Python console and run.

What it does:
    - Reads style-resolved.json (a full MapLibre GL style with real tile URLs).
    - Creates one QgsVectorTileLayer per vector source.
    - Applies the MapLibre GL style to each layer via QgsMapBoxGlStyleConverter
      (QGIS translates filters, colors, zoom steps; complex interpolations become steps).
    - Adds the terrain raster-DEM source as a plain XYZ raster layer.
    - Adds all layers to the current QGIS project in one operation.
    - Optionally saves a .qgz project file (set SAVE_PROJECT below).

Layer ordering note:
    Sources are added in bottom-to-top order matching style.json draw order.
    QGIS renders layers top-to-bottom in the Layers panel, so the script reverses
    the order when adding so the final panel order matches the web map.
"""

import json
from pathlib import Path

# ── USER SETTINGS ─────────────────────────────────────────────────────────────

# Path to the resolved style JSON (generated by resolve_style.py).
STYLE_PATH = '/Users/matthewheaton/GitHub/0_CIESIN/GRID3_mapTiles/pmtiles/app/public/style-resolved.json"'

# Set to a .qgz path to auto-save the project after import, or None to skip.
SAVE_PROJECT: "str | None" = None
# Example: SAVE_PROJECT = str(Path.home() / "ciesin_tiles.qgz")

# ── IMPORTS ───────────────────────────────────────────────────────────────────

from qgis.core import (  # noqa: E402
    QgsMapBoxGlStyleConverter,
    QgsMapBoxGlStyleConversionContext,
    QgsProject,
    QgsRasterLayer,
    QgsVectorTileLayer,
)

# ── HELPERS ───────────────────────────────────────────────────────────────────

def _source_style(style: dict, source_id: str) -> dict:
    """Return a copy of the style containing only layers that belong to source_id.

    Background/sky layers (no 'source' field) are excluded — QGIS's converter
    ignores them anyway, and keeping them would pollute every layer's symbology.
    """
    filtered = dict(style)
    filtered["layers"] = [
        layer for layer in style["layers"]
        if layer.get("source") == source_id
    ]
    return filtered


def _make_vtl(source_id: str, tile_url: str, maxzoom: int, style: dict) -> "QgsVectorTileLayer | None":
    uri = f"type=xyz&url={tile_url}&zmax={maxzoom}&zmin=0"
    layer = QgsVectorTileLayer(uri, source_id)
    if not layer.isValid():
        print(f"  warn  {source_id!r}: layer not valid (URL may be unreachable)")
        return None

    source_style = _source_style(style, source_id)
    n = len(source_style["layers"])
    if n == 0:
        print(f"  warn  {source_id!r}: no style layers found — layer added unstyled")
        return layer

    ctx = QgsMapBoxGlStyleConversionContext()
    conv = QgsMapBoxGlStyleConverter()
    result = conv.convert(source_style, ctx)
    if result == QgsMapBoxGlStyleConverter.Success:
        layer.setRenderer(conv.renderer().clone())
        layer.setLabeling(conv.labeling().clone())
        print(f"  ok    {source_id!r} ({n} style rule(s))")
    else:
        print(f"  warn  {source_id!r}: style conversion failed ({result}), layer added unstyled")

    return layer


def _make_raster(source_id: str, tile_url: str, maxzoom: int) -> "QgsRasterLayer | None":
    # QGIS WMS/XYZ raster URI format
    encoded_url = tile_url.replace("{", "%7B").replace("}", "%7D")
    uri = (
        f"type=xyz"
        f"&url={encoded_url}"
        f"&zmax={maxzoom}"
        f"&zmin=0"
        f"&crs=EPSG:3857"
    )
    layer = QgsRasterLayer(uri, source_id, "wms")
    if not layer.isValid():
        print(f"  warn  {source_id!r}: raster layer not valid")
        return None
    return layer


# ── MAIN ──────────────────────────────────────────────────────────────────────

def run():
    style_path = Path(STYLE_PATH)
    if not style_path.exists():
        print(f"ERROR: style file not found: {style_path}")
        print("Run:  python preprocessing/scripts/resolve_style.py --env dev")
        return

    with open(style_path) as f:
        style = json.load(f)

    project = QgsProject.instance()
    added = []

    # Collect source IDs in style draw order so we can reverse for the Layers panel.
    source_order = list(style["sources"].keys())

    for source_id in source_order:
        source_def = style["sources"][source_id]
        stype = source_def.get("type", "")
        tiles = source_def.get("tiles", [])

        if not tiles:
            print(f"  skip  {source_id!r}: no tile URL (still a placeholder)")
            continue

        tile_url = tiles[0]
        maxzoom = source_def.get("maxzoom", 14)

        if stype == "vector":
            layer = _make_vtl(source_id, tile_url, maxzoom, style)
        elif stype in ("raster", "raster-dem"):
            layer = _make_raster(source_id, tile_url, maxzoom)
        else:
            print(f"  skip  {source_id!r}: unsupported source type {stype!r}")
            continue

        if layer is not None:
            added.append(layer)
            if stype in ("raster", "raster-dem"):
                print(f"  ok    {source_id!r} ({stype})")

    if not added:
        print("No layers added.")
        return

    # Add in reverse so the Layers panel order matches the web-map draw order
    # (QGIS renders top-of-panel first, web map draws bottom of layers list first).
    for layer in reversed(added):
        project.addMapLayer(layer)

    print(f"\nAdded {len(added)} layer(s) to QGIS project.")

    if SAVE_PROJECT:
        project.write(SAVE_PROJECT)
        print(f"Project saved to {SAVE_PROJECT}")


run()
