"""
resolve_style.py — Bake real tile URLs into style.json for QGIS / standalone use.

Usage:
    python resolve_style.py                # defaults to --env dev
    python resolve_style.py --env prod
    python resolve_style.py --env dev --out /path/to/output.json

Reads:
    - ../../pmtiles/app/src/style.json      (MapLibre GL style with empty tiles:[])
    - sources.json                          (JSON mirror of sources.ts)

Writes:
    - ../../pmtiles/app/public/style-resolved.json  (default output)

Notes:
    - The 'dem' source in style.json is populated from the 'terrain' archive (same tiles,
      type stays 'raster-dem' for MapLibre; QGIS users should ignore it or add it as
      a plain XYZ raster layer manually).
    - The 'contours' source is runtime-generated by maplibre-contour and has no standalone
      tile endpoint — it is removed from the resolved style.
    - Any source in style.json that has no matching key in sources.json is left unchanged
      (empty tiles:[]) with a warning.
"""

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
REPO_ROOT = HERE.parent.parent

STYLE_IN  = REPO_ROOT / "pmtiles" / "app" / "src" / "style.json"
SOURCES_JSON = HERE / "sources.json"
STYLE_OUT_DEFAULT = REPO_ROOT / "pmtiles" / "app" / "public" / "style-resolved.json"

# style.json source key -> sources.json source key (when they differ)
SOURCE_KEY_MAP = {
    "dem": "terrain",  # dem uses terrain tiles; type stays raster-dem in the output
}

# Sources that are runtime-generated and have no real tile endpoint — drop them.
RUNTIME_SOURCES = {"contours"}


def resolve(env: str, out_path: Path) -> None:
    with open(STYLE_IN) as f:
        style = json.load(f)

    with open(SOURCES_JSON) as f:
        manifest = json.load(f)

    worker_url: str = manifest["workerUrls"][env]
    source_defs: dict = manifest["sources"]

    resolved_sources = {}
    for style_key, style_src in style["sources"].items():
        if style_key in RUNTIME_SOURCES:
            print(f"  skip  {style_key!r} (runtime-generated, no tile endpoint)")
            continue

        lookup_key = SOURCE_KEY_MAP.get(style_key, style_key)

        if lookup_key not in source_defs:
            print(f"  warn  {style_key!r} not found in sources.json — left with empty tiles")
            resolved_sources[style_key] = style_src
            continue

        src = source_defs[lookup_key]
        tile_url = f"{worker_url}/{src['archive']}/{{z}}/{{x}}/{{y}}.{src['ext']}"

        resolved_src = dict(style_src)
        resolved_src["tiles"] = [tile_url]
        resolved_src["attribution"] = src["attribution"]
        resolved_src["maxzoom"] = src["maxzoom"]

        resolved_sources[style_key] = resolved_src
        print(f"  ok    {style_key!r} -> {tile_url}")

    style["sources"] = resolved_sources

    # Remove any layer that references a dropped source (e.g. contours)
    kept_layers = [
        layer for layer in style.get("layers", [])
        if layer.get("source") not in RUNTIME_SOURCES
    ]
    dropped = len(style["layers"]) - len(kept_layers)
    if dropped:
        print(f"  drop  {dropped} layer(s) that reference removed runtime sources")
    style["layers"] = kept_layers

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(style, f, indent=2, ensure_ascii=False)

    print(f"\nWrote {out_path}")
    print(f"  {len(resolved_sources)} sources, {len(kept_layers)} layers")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--env", choices=["dev", "prod"], default="dev",
                        help="Which worker URL to use (default: dev)")
    parser.add_argument("--out", type=Path, default=STYLE_OUT_DEFAULT,
                        help="Output path for the resolved style JSON")
    args = parser.parse_args()

    print(f"Resolving style for env={args.env!r} ...")
    resolve(args.env, args.out)


if __name__ == "__main__":
    main()
